<a href="https://colab.research.google.com/github/srihitha-05/Machine-Learning/blob/main/LAB1_AP23110010120.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [2]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [3]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [4]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
chessboard = np.zeros((10, 10), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [5]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [6]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
arr = np.zeros((1000, 1000), dtype=np.float64)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Item size (bytes):", arr.itemsize)
print("Total bytes:", arr.nbytes)

Shape: (1000, 1000)
Size: 1000000
Item size (bytes): 8
Total bytes: 8000000


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [7]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [8]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a[[0, -1]] = a[[-1, 0]]
print(a)

[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [9]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [10]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
arr3d = np.arange(24).reshape(2, 3, 4)
flat_ravel = arr3d.ravel()     # View
flat_flatten = arr3d.flatten() # Copy

print("Original shape:", arr3d.shape)
print("Ravel:", flat_ravel)
print("Flatten:", flat_flatten)

# Change an element in ravel view
flat_ravel[0] = 999
print("After modifying ravel -> Original array changes:\n", arr3d)
print("Flatten remains unchanged:", flat_flatten)

Original shape: (2, 3, 4)
Ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
After modifying ravel -> Original array changes:
 [[[999   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]
Flatten remains unchanged: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [11]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [12]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
parts = np.array_split(xy, 2)
print(parts[0])
print(parts[1])

[1 3 5]
[2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [13]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [14]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
degrees = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(degrees)  # converts degrees to radians
sin_values = np.sin(radians)   # sine for each radian value
print("Radians:", radians)
print("Sine:", sin_values)


Radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [15]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [16]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
table = np.arange(1, 11)[:, np.newaxis] * np.arange(1, 11)
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [17]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [18]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
p25 = np.percentile(data, 25)
p50 = np.percentile(data, 50)
p75 = np.percentile(data, 75)
print("25th:", p25, "Median:", p50, "75th:", p75)


25th: 30.0 Median: 58.5 75th: 75.0


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [19]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [20]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
rolls = np.random.randint(1, 7, size=100)  # 1 to 6
prop_6 = np.mean(rolls == 6)
print("Proportion of 6s:", prop_6)


Proportion of 6s: 0.14


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [21]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [22]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
from numpy.lib import recfunctions as rfn

heights = [165.0, 180.0]
people_with_height = rfn.append_fields(people, 'height', heights, dtypes='f4', usemask=False)
print(people_with_height)


[('Alice', 25, 55. , 165.) ('Bob', 30, 85.5, 180.)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [23]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [24]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)

Eigenvalues: [ 1.19932903  0.22872581 -0.01701285]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [25]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [26]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
np.savetxt("data.csv", data, delimiter=",")
loaded_data = np.loadtxt("data.csv", delimiter=",")
print(loaded_data)


[[85. 64. 51. 27.]
 [31.  5.  8.  2.]
 [18. 81. 65. 91.]
 [50. 61. 97. 73.]
 [63. 54. 56. 93.]]


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [27]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [28]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
mondays = np.sum(dates.astype('datetime64[D]').astype(int) % 7 == 0)
print("Number of Mondays:", mondays)


Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [29]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [30]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
arr2d = np.array([[1, np.nan, 3],
                  [4, 5, np.nan],
                  [7, 8, 9]])

col_means = np.nanmean(arr2d, axis=0)
inds = np.where(np.isnan(arr2d))
arr2d[inds] = np.take(col_means, inds[1])
print(arr2d)


[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [32]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))

columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [37]:
import pandas as pd

In [46]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.

fitness_df = pd.DataFrame(fitness)

fitness_df['date'] = pd.to_datetime(fitness_df['date'], dayfirst=True, errors='coerce')

monthly_steps = fitness_df.groupby(fitness_df['date'].dt.to_period('M'))['step_count'].sum()
print("\n--- Monthly Step Totals ---")
print(monthly_steps)

fitness_df['hours_of_sleep'] = pd.to_numeric(fitness_df['hours_of_sleep'], errors='coerce')
fitness_df['mood'] = pd.to_numeric(fitness_df['mood'], errors='coerce')
correlation = fitness_df[['hours_of_sleep', 'mood']].corr().iloc[0, 1]
print(f"\nSleep vs Mood correlation: {correlation:.2f}")


weekly_summary = fitness_df.groupby(fitness_df['date'].dt.to_period('W')).agg({
    'step_count': 'mean',
    'hours_of_sleep': 'mean',
    'mood': 'mean'
})
print("\n--- Weekly Summary ---")
print(weekly_summary)



--- Monthly Step Totals ---
date
2017-10     79051
2017-11    103071
2017-12     89565
2018-01     10163
Freq: M, Name: step_count, dtype: int64

Sleep vs Mood correlation: 0.21

--- Weekly Summary ---
                        step_count  hours_of_sleep        mood
date                                                          
2017-10-02/2017-10-08  3843.333333        6.000000  133.333333
2017-10-09/2017-10-15  3401.428571        5.571429  114.285714
2017-10-16/2017-10-22  2952.714286        6.428571  128.571429
2017-10-23/2017-10-29  2326.142857        5.571429  214.285714
2017-10-30/2017-11-05  2942.571429        5.142857  285.714286
2017-11-06/2017-11-12  4459.571429        4.714286  285.714286
2017-11-13/2017-11-19  2530.571429        5.571429  285.714286
2017-11-20/2017-11-26  3979.857143        5.714286  300.000000
2017-11-27/2017-12-03  2671.571429        6.428571  257.142857
2017-12-04/2017-12-10  3025.428571        5.428571  214.285714
2017-12-11/2017-12-17  3232.571429       

## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*